# -*- coding: utf-8 -*-
"""claude hackathon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzJDJ_0SME-oZyuiNDZIFZMntZAWFg1S
"""

!pip install anthropic

import anthropic

my_key = "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"
client = anthropic.Anthropic(api_key=my_key)

try:
    message = client.messages.create(
        model="claude-sonnet-4-5-20250929",
        max_tokens=1000,
        messages=[
            {"role": "user", "content": "Act as a management for a company"}
        ],
    )
    print(message.content[0].text)
except anthropic.APIError as e:
    print(f"Error: {e}")

"""# Scarpping the web"""

pip install requests beautifulsoup4

!pip install --upgrade gensim

!pip install youtube-transcript-api

import requests
from bs4 import BeautifulSoup

def youtube_description(url: str):
    html = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}).text
    soup = BeautifulSoup(html, "html.parser")
    title = soup.find("meta", property="og:title")["content"]
    desc  = soup.find("meta", property="og:description")["content"]
    return title, desc

from youtube_transcript_api import YouTubeTranscriptApi
from urllib.parse import urlparse, parse_qs

def is_appropriate(url, role):
    if "youtube.com" in url:
        title, desc = youtube_description(url)
        print("Title:", title)
        print("Description:", desc)
        prompt = (
            f"Review this webpage this {role} employee is on. "
            f"Website Summary: Title is \"{title}\", Description: {desc}. "
            f"State whether this is somewhat related or topically appropriate to his work. Start with an answer Yes or No. "
            f"Give one concise statement stating your reasoning with quick references the title and key parts of the description"
            f"Then give another short sentence stating two exceptions to your answer."
        )

        message = client.messages.create(
            model="claude-sonnet-4-5-20250929",
            max_tokens=1000,
            messages=[{"role": "user", "content": prompt}],
        )

        rep = message.content[0].text.strip()
        flag = rep.split()[0] == "**No**"

    else:
        html = requests.get(url, timeout=30).text
        prompt = (
            f"What is the following webpage:\n\n{html[:10000]} that this {role} employee is on.\n\n"
            f"State whether this it somewhat related or topically appropriate to his work. Start with an answer Yes or No. "
            f"Then give one concise statement stating your reasoning with quick references to the title and key parts of the description"
            f"Then give another short sentence stating two exceptions for this context"
        )

        message = client.messages.create(
            model="claude-sonnet-4-5-20250929",
            max_tokens=1000,
            messages=[{"role": "user", "content": prompt}],
        )

        rep = message.content[0].text.strip()
        flag = rep.split()[0] == "**No**"

    print("Response:", rep)
    return flag, rep

#url = input('url test: ')
#role = input('the workers role: ')
#print(is_appropriate(url, role))
#is_appropriate(url, role)

# Function to test if an url is appropriate:
#url = input('url test: ')
#role = input('the workers role: ')
#print(is_appropriate(url, role))
#is_appropriate(url)
#parameters: url, role description
# return messages (review), flag
# if flag is true -> stamp the time and send the review
# when flag is true -> take the action (new variable) -> just update the database
# when hr update the review -> set flag to false -> clear the review

"""# Setting up firebase

"""

!pip install streamlit google-cloud-firestore google-auth

# test if .json file is upload
import os
print(os.path.exists("/content/firebase_key.json"))

#set the environment

import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/firebase_key.json"
os.environ["CONTENTCHECK_COLLECTION"] = "workerstatus"

# Commented out IPython magic to ensure Python compatibility.
# # @title
# """
# %%writefile app.py
# import os
# from datetime import datetime
# from typing import Any, Dict, List
# 
# import streamlit as st
# from google.cloud import firestore
# from google.oauth2 import service_account
# 
# COLLECTION_NAME = os.getenv("CONTENTCHECK_COLLECTION", "workerstatus")
# SERVICE_ACCOUNT_FILE = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "firebase_key.json")
# 
# def get_db() -> firestore.Client:
#     if not os.path.exists(SERVICE_ACCOUNT_FILE):
#         st.stop()
#     creds = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE)
#     return firestore.Client(credentials=creds, project=creds.project_id)
# 
# def fmt_ts(ts) -> str:
#     if ts is None:
#         return ""
#     try:
#         dt = ts.to_datetime() if hasattr(ts, "to_datetime") else ts
#         return dt.strftime("%Y-%m-%d %H:%M:%S")
#     except Exception:
#         return str(ts)
# 
# def fetch_rows(db: firestore.Client) -> List[Dict[str, Any]]:
#     rows: List[Dict[str, Any]] = []
#     for d in db.collection(COLLECTION_NAME).stream():
#         x = d.to_dict() or {}
#         rows.append({
#             "_id": d.id,
#             "ID": x.get("ID", ""),
#             "role": x.get("role", x.get("team role", "")),
#             "last_flagged": x.get("last flagged", x.get("last_flagged")),
#             "Review": x.get("Review", x.get("content review", "")),
#             "link": x.get("link", ""),
#             "flag": bool(x.get("flag", False)),
#             "action": x.get("action", ""),
#         })
#     rows.sort(key=lambda r: r.get("last_flagged") or datetime.fromtimestamp(0), reverse=True)
#     return rows
# 
# def write_action(db: firestore.Client, doc_id: str, value: str) -> None:
#     db.collection(COLLECTION_NAME).document(doc_id).update({
#         "action": value,
#         "flag": False,
#         "action_timestamp": firestore.SERVER_TIMESTAMP,
#     })
# 
# def toggle_flag_true(db: firestore.Client, doc_id: str) -> None:
#     db.collection(COLLECTION_NAME).document(doc_id).update({"flag": True})
# 
# st.set_page_config(page_title="Manager Dashboard", layout="wide")
# st.title("Manager Dashboard")
# st.caption(f"Firestore collection: `{COLLECTION_NAME}` · Manual refresh")
# 
# st.button("Refresh data")
# 
# COLLECTION_NAME = st.text_input(
#     "Firestore collection name",
#     value=COLLECTION_NAME,
#     help="Change if your collection is not 'workerstatus' or 'contentcheck'.",
# ).strip() or COLLECTION_NAME
# 
# try:
#     db = get_db()
#     rows = fetch_rows(db)
#     if not rows:
#         st.info(f"No documents found in collection '{COLLECTION_NAME}'.")
# except Exception as e:
#     st.error(f"Failed to read Firestore collection '{COLLECTION_NAME}': {e}")
#     rows = []
# 
# st.subheader("Worker status")
# st.dataframe([
#     {
#         "ID": r["ID"],
#         "role": r["role"],
#         "last flagged": fmt_ts(r["last_flagged"]),
#         "flag": r["flag"],
#         "action": r["action"],
#         "link": r["link"] or "—",
#         "review": (r["Review"] or "")[:60] + ("…" if len(r.get("Review", "")) > 60 else ""),
#     }
#     for r in rows
# ], use_container_width=True, hide_index=True)
# 
# st.divider()
# 
# for r in rows:
#     with st.expander(f"{r['ID']} · {r['role']} · Flag: {r['flag']}", expanded=r["flag"]):
#         st.write(f"**Last flagged:** {fmt_ts(r['last_flagged'])}")
#         if r["link"]:
#             st.markdown(f"[Open link]({r['link']})")
#         st.write(f"**Review:** {r['Review'] or '—'}")
#         st.write(f"**Last action:** {r['action'] or '—'}")
# 
#         if r["flag"]:
#             choice = st.radio("Action", ["block", "warn", "accept"], key=f"act_{r['_id']}", horizontal=True)
#             if st.button("Submit", key=f"submit_{r['_id']}"):
#                 write_action(db, r["_id"], choice)
#                 st.success(f"Saved '{choice}' and reset flag.")
#                 st.rerun()
#         else:
#             c1, c2 = st.columns([1, 1])
#             with c1:
#                 st.caption("Flag is False.")
#             with c2:
#                 if st.button("Set Flag True", key=f"flag_{r['_id']}"):
#                     toggle_flag_true(db, r["_id"])
#                     st.success("Flag set to True.")
#                     st.rerun()
# """

!pip install google-cloud-firestore



from tabulate import tabulate
import os
import time
from google.cloud import firestore
from google.oauth2 import service_account

# set environment variables
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/firebase_key.json"
os.environ["CONTENTCHECK_COLLECTION"] = "workerstatus"

# use them
SERVICE_ACCOUNT_FILE = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
COLLECTION_NAME = os.getenv("CONTENTCHECK_COLLECTION")

creds = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE)
db = firestore.Client(credentials=creds, project=creds.project_id)

docs = db.collection(COLLECTION_NAME).stream()

def run():
  rows = []
  for d in db.collection(COLLECTION_NAME).stream():
      data = d.to_dict()
      rows.append([
          d.id,
          data.get("ID", ""),
          data.get("role", data.get("team role", "")),
          data.get("link", "—")
      ])

  role = rows[0][2]
  link = rows[0][3]
  flag, rep = is_appropriate(link, role)
  print(flag)
  doc_id = 'workerstatus'
  if flag == True:
    db.collection(COLLECTION_NAME).document(doc_id).update({
        "flag": flag,
        "Review": rep
    })
  else:
      db.collection(COLLECTION_NAME).document(doc_id).update({
        "Review": ''
    })

for i in range(10):
  print(f"what employee doing time {i+1}")
  run()
  time.sleep(20)

print(link)
print(tabulate(rows, headers=["Doc ID", "ID", "Role", "Link"]))

link = rows[0][3]

#is_appropriate(url)
#parameters: url, role description
# return messages (review), flag
# if flag is true -> stamp the time and send the review
# when flag is true -> take the action (new variable) -> just update the database
# when hr update the review -> set flag to false -> clear the review

role = rows[0][2]
link = rows[0][3]
flag, rep = is_appropriate(link, role)
print(flag)
doc_id = 'workerstatus'
if flag == True:
  db.collection(COLLECTION_NAME).document(doc_id).update({
      "flag": flag,
      "Review": rep
  })
else:
    db.collection(COLLECTION_NAME).document(doc_id).update({
      "Review": ''
  })

#display the database after updating

print(tabulate(rows, headers=["Doc ID", "ID", "Role", "Flag", "Action", "Link"]))